### Encoding

```swift
struct User: Encodable {
    let name: String
    let age: Int
}

let jack = [
    User(name: "휴", age: 24),
    User(name: "잭", age: 21),
    User(name: "브랜", age: 22),
    User(name: "덴", age: 22)
]

let encoder = JSONEncoder()
do {
    let result = try encoder.encode(jack)
    print(result)
    guard let jsonString = String(data: result, encoding: .utf8) else {
        fatalError("error")
    }
    print(jsonString)
    // [{"name":"휴","age":24},{"name":"잭","age":22},{"age":22,"name":"브랜"},{"name":"덴","age":22}]
} catch {
    print(error.localizedDescription)
}
```

만약 JsonString을 형식에 맞게 이쁘게 출력하고 싶다면

아래 코드를 사용할 수 있다.

```swift
let encoder = JSONEncoder()
encoder.outputFormatting = .prettyPrinted
```

Date타입을 encoding하게된다면 아래와 같이 encoding된다.

```swift
{
  "age" : 24,
  "birth" : 760928589.524205,
  "name" : "휴"
}
```

이렇게 된다면 서버의 할 일이 많아지기 때문에 조금 수정할 필요가 있다.

```swift
encoder.dateEncodingStrategy = .iso8601
```

해당 코드를 추가하게 된다면 날짜와 시간과 관련된 데이터 교환을 다루는 국제 표준 값으로 표현할 수 있다.

```swift
let encoder = JSONEncoder()
let format = DateFormatter()
format.dateFormat = "MM월 dd일, yyyy년"
encoder.dateEncodingStrategy = .formatted(format)
```

혹은 위와 같이 내가 원하는 형식의 dateFormat으로 바꾸어서 보낼 수 있다.

### 오류 처리 패턴. 에러 핸들링

do - try catch가 왜 필요할까?

if-else, switch는 `선택`의 의미인 것 같다. 

하지만 do - try catch는 사용자의 선택은 아니고 `에러`의 관점인 것 같다. 

당연히 잘 되어야하는 것인데 오류가 발생했다의 관점이 아닐까? 라는 생각이다.

그리고 추가적인 내 생각은 결국 func 내부에서 에러를 처리하기 위해 if-else, switch를 통해 오류라는 것을 반환하기 위해서는 결국에 값을 보내야한다. 그 값이 빈 배열이 되었든, 빈 문자열이 되었든 우리는 이러한 값을 에러라고 생각하자라는 정의가 필요할 것 같다.

하지만 빈 배열과 빈 문자열을 사용할 수도 있고 과연 이러한 값이 문제라고 할 수 있는가? 나는 아닌 것 같다.

따라서, 의미가 없을 수도 있는 값을 꼭 반환하지 않아도 되는 `에러`라는 것을 명시적으로 던지는 것은 중요한 것 같다.

에러 타입의 정의

```swift
// 컴파일러가 오류의 타입을 인정하게 된다.
enum ValidationError: Error {
    case emptyString
    case isNotInt
    case isNotDate
}
```

`throwing function` - throw 키워드로 표시된 함수

- 에러를 발생시킬 수 있다는 것을 알리기 위해 `throws` 키워드를 함수 선언부의 파라미터 뒤에 붙인다.

```swift
func validateUserInputError (text: String) throws -> Bool {
    guard !(text.isEmpty) else {
        throw ValidationError.emptyString
    }
    
    guard Int(text) != nil else {
        throw ValidationError.isNotInt
    }
    
    guard checkDateFormat(text: text) else {
        throw ValidationError.isNotDate
    }
    
    return true
}
```

- 오류 대응을 할 수 없는 코드 - 앱이 터진다.

```swift
let result = try validateUserInputError(text: <#T##String#>)
```

- 오류 대응을 할 수 없는 코드 - 앱이 터지진 않는다. (어떤 오류인지 알 수 없음)

```swift
let result = try? validateUserInputError(text: <#T##String#>)
```

- 오류 대응을 할 수 있는 코드 - 어떤 오류인지 알 수 있다.

```swift
do {
    let result = try validateUserInputError(text: <#T##String#>)
} catch ValidationError.isNotDate {
    print("명시적으로 error를 구분할 수 있다.")
} catch {
    // 모든 에러에 대해서 받을수 있다.
    switch error as? ValidationError {
    case .emptyString:
        print("")
    case .isNotInt:
        print("")
    case .isNotDate:
        print("")
    default:
        print("")
    }
}
```

### Typed Throws

<aside>
💡

**Error 타입을 구체적으로 정의할 수 없어서 타입캐스팅을 활용해서 처리해야한다.**

</aside>

⇒ Swift6 - 오류 타입에 대해 구체적인 정의 제공

```swift
func validateUserInputError (text: String) throws(ValidationError) -> Bool {
    guard !(text.isEmpty) else {
        throw ValidationError.emptyString
    }
    
    guard Int(text) != nil else {
        throw ValidationError.isNotInt
    }
    
    guard checkDateFormat(text: text) else {
        throw ValidationError.isNotDate
    }
    
    return true
}
```

```swift
do {
    let result = try validateUserInputError(text: <#T##String#>)
} catch {
    switch error {
    case .emptyString:
        print("")
    case .isNotInt:
        print("")
    case .isNotDate:
        print("")
    }
}
```

### Property wrapper

```swift
@propertyWrapper
struct UserDefaultsProperty<T> {
    let key: String
    let defaultValue: T
    
    private(set) var projectedValue: Bool = false
    
    var wrappedValue: T {
        get {
            UserDefaults.standard.object(forKey: key) as? T ?? defaultValue
        }
        set {
            UserDefaults.standard.setValue(newValue, forKey: key)
        }
    }
}

enum UserDefaultsManager {
    
    enum Key: String {
        case age
        case first
        case lask
    }
    
    @UserDefaultsProperty(key: Key.age.rawValue, defaultValue: "")
    static var age
}

UserDefaultsManager.age // wrappedValue
UserDefaultsManager.$age // projectedValue - wrapper의 부가적인 상태를 외부에 보여주려고 할 때
```

Property wrapper에서 자동적으로 구조체를 호출 시에 대신 호출될 프로퍼티를 지정하는 것이다.

다른 사용 예시코드

```swift
@propertyWrapper
struct Decimal {
    
    var money: String
    var projectedValue = ""
    var wrappedValue: String {
        get {
            return Int(money)!.formatted(.number) + "원"
        } set {
            money = newValue
            projectedValue = "당신이 이체한 금액은 \(newValue)입니다."
        }
    }
}

struct Example {
    @Decimal(money: "7000")
    var number
}

var example = Example()
example.number //"7,000원"
example.number = "32000"
example.number //"32,000원"
example.$number // "당신이 이체한 금액은 32000입니다."
```

### String의 index조회하기 - subcript

```swift
let nick = "안녕하세요 반값습니다."
nick[2] // "하"를 출력하고 싶음.
// 'subscript(_:)' is unavailable: cannot subscript String with an Int, use a String.Index instead.
```

하지만 인덱스로 접근할 수 없음.

String에는 `subscript(_:)` 문법이 적용되어있지 않기 때문이다.

```swift
extension String {
    subscript(_ idx: Int) -> String? {
        guard (0..<count).contains(idx) else {
            return nil
        }
        
        let result = index(startIndex, offsetBy: idx)
        return String(self[result])
    }
}

let nick = "안녕하세요 반값습니다."
nick[2] // "하"
```

또 다른 사용 예시

```swift
struct UserPhoneList {
    var contacts = [
        "01012341234",
        "01045674567",
        "01078907890"
    ]
    
    subscript(idx: Int) -> String {
        get {
            return self.contacts[idx]
        } set {
            self.contacts[idx] = newValue
        }
    }
}

let userPhoneList = UserPhoneList()
userPhoneList[1] // "01045674567"
```
